### ISSUE TITLE
binlog_reader  on ubuntu 18.04 (Invalid Format_description event: number_of_event_types 39 > 38)

### ISSUE THREAD

**Issue by hellracer** [sysown/proxysql_mysqlbinlog#2]
`proxysql_binlog_reader -h 127.0.0.1 -u devel -p xxxxxxxxx -P 3306 -l 6020 -L /var/log/binlog_reader.log`
```
Starting ProxySQL MySQL Binlog
Sucessfully started
Angel process started ProxySQL MySQL Binlog process 20563
2019-05-09 23:25:28 [INFO] Initializing client...
55931b0c-59cc-11e9-b31f-f23c916ba36d:1-1056,1f83ec0b-704d-11e9-b0b3-00e066f46a32:1-2137
2019-05-09 23:25:28 [INFO] Reading binlogs...
Invalid Format_description event: number_of_event_types 39 > 38
Met exception in get_remote_binlog cycle. Message: Invalid Format_description event
read_event(): end of data
```
my.cnf

```
[mysqld]
pid-file        = /var/run/mysqld/mysqld.pid
socket          = /var/run/mysqld/mysqld.sock
datadir         = /var/lib/mysql
log-error       = /var/log/mysql/error.log

server-id = 2
skip_name_resolve = 1
log-bin = log-bin
innodb_dedicated_server=1
relay-log = relay-log
gtid-mode=ON
enforce-gtid-consistency
session_track_gtids=OWN_GTID
log_slave_updates
binlog_format=ROW
```
```
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 32
Server version: 8.0.15-6 Percona Server (GPL), Release '6', Revision '63abd08'

Copyright (c) 2009-2019 Percona LLC and/or its affiliates
Copyright (c) 2000, 2019, Oracle and/or its affiliates. All rights reserved.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.
mysql> show global variables like 'binlog%';
+------------------------------------------------+--------------+
| Variable_name                                  | Value        |
+------------------------------------------------+--------------+
| binlog_cache_size                              | 32768        |
| binlog_checksum                                | CRC32        |
| binlog_direct_non_transactional_updates        | OFF          |
| binlog_encryption                              | OFF          |
| binlog_error_action                            | ABORT_SERVER |
| binlog_expire_logs_seconds                     | 2592000      |
| binlog_format                                  | ROW          |
| binlog_group_commit_sync_delay                 | 0            |
| binlog_group_commit_sync_no_delay_count        | 0            |
| binlog_gtid_simple_recovery                    | ON           |
| binlog_max_flush_queue_time                    | 0            |
| binlog_order_commits                           | ON           |
| binlog_rotate_encryption_master_key_at_startup | OFF          |
| binlog_row_event_max_size                      | 8192         |
| binlog_row_image                               | FULL         |
| binlog_row_metadata                            | MINIMAL      |
| binlog_row_value_options                       |              |
| binlog_rows_query_log_events                   | OFF          |
| binlog_skip_flush_commands                     | OFF          |
| binlog_space_limit                             | 0            |
| binlog_stmt_cache_size                         | 32768        |
| binlog_transaction_dependency_history_size     | 25000        |
| binlog_transaction_dependency_tracking         | COMMIT_ORDER |
+------------------------------------------------+--------------+
23 rows in set (0.00 sec)

mysql> 
```

**Comment by renecannao** [comment]
It would be very useful if you give us as much details as possible about the MySQL server, specifically version and all binlog related variables

**Comment by Blastnsmash** [comment]
Same issue on Ubuntu 18.04

Angel process started ProxySQL MySQL Binlog process 31185
2019-07-10 16:11:03 [INFO] Initializing client...
c4dff54f-9a05-11e9-a07b-0242ac110003:1-56998,88fc15d5-9a04-11e9-85fe-0242ac110003:1-53369
2019-07-10 16:11:03 [INFO] Reading binlogs...
Invalid Format_description event: number_of_event_types 39 > 38
Met exception in get_remote_binlog cycle. Message: Invalid Format_description event


mysql> show variables like '%version%'\G;
*************************** 1. row ***************************
Variable_name: group_replication_allow_local_lower_version_join
        Value: OFF
*************************** 2. row ***************************
Variable_name: immediate_server_version
        Value: 999999
*************************** 3. row ***************************
Variable_name: innodb_version
        Value: 8.0.16
*************************** 4. row ***************************
Variable_name: original_server_version
        Value: 999999
*************************** 5. row ***************************
Variable_name: protocol_version
        Value: 10
*************************** 6. row ***************************
Variable_name: slave_type_conversions
        Value:
*************************** 7. row ***************************
Variable_name: tls_version
        Value: TLSv1,TLSv1.1,TLSv1.2
*************************** 8. row ***************************
Variable_name: version
        Value: 8.0.16
*************************** 9. row ***************************
Variable_name: version_comment
        Value: MySQL Community Server - GPL
*************************** 10. row ***************************
Variable_name: version_compile_machine
        Value: x86_64
*************************** 11. row ***************************
Variable_name: version_compile_os
        Value: Linux
*************************** 12. row ***************************
Variable_name: version_compile_zlib
        Value: 1.2.11

mysql> show global variables like '%gtid%'\G;
*************************** 1. row ***************************
Variable_name: binlog_gtid_simple_recovery
        Value: ON
*************************** 2. row ***************************
Variable_name: enforce_gtid_consistency
        Value: ON
*************************** 3. row ***************************
Variable_name: group_replication_gtid_assignment_block_size
        Value: 1000000
*************************** 4. row ***************************
Variable_name: gtid_executed
        Value: 88fc15d5-9a04-11e9-85fe-0242ac110003:1-53369,
c4dff54f-9a05-11e9-a07b-0242ac110003:1-56998
*************************** 5. row ***************************
Variable_name: gtid_executed_compression_period
        Value: 1000
*************************** 6. row ***************************
Variable_name: gtid_mode
        Value: ON
*************************** 7. row ***************************
Variable_name: gtid_owned
        Value:
*************************** 8. row ***************************
Variable_name: gtid_purged
        Value:
*************************** 9. row ***************************
Variable_name: session_track_gtids
        Value: OWN_GTID



mysql> show variables like '%binlog%'\G;
*************************** 1. row ***************************
Variable_name: binlog_cache_size
        Value: 32768
*************************** 2. row ***************************
Variable_name: binlog_checksum
        Value: NONE
*************************** 3. row ***************************
Variable_name: binlog_direct_non_transactional_updates
        Value: OFF
*************************** 4. row ***************************
Variable_name: binlog_encryption
        Value: OFF
*************************** 5. row ***************************
Variable_name: binlog_error_action
        Value: ABORT_SERVER
*************************** 6. row ***************************
Variable_name: binlog_expire_logs_seconds
        Value: 2592000
*************************** 7. row ***************************
Variable_name: binlog_format
        Value: ROW
*************************** 8. row ***************************
Variable_name: binlog_group_commit_sync_delay
        Value: 0
*************************** 9. row ***************************
Variable_name: binlog_group_commit_sync_no_delay_count
        Value: 0
*************************** 10. row ***************************
Variable_name: binlog_gtid_simple_recovery
        Value: ON
*************************** 11. row ***************************
Variable_name: binlog_max_flush_queue_time
        Value: 0
*************************** 12. row ***************************
Variable_name: binlog_order_commits
        Value: ON
*************************** 13. row ***************************
Variable_name: binlog_rotate_encryption_master_key_at_startup
        Value: OFF
*************************** 14. row ***************************
Variable_name: binlog_row_event_max_size
        Value: 8192
*************************** 15. row ***************************
Variable_name: binlog_row_image
        Value: FULL
*************************** 16. row ***************************
Variable_name: binlog_row_metadata
        Value: MINIMAL
*************************** 17. row ***************************
Variable_name: binlog_row_value_options
        Value:
*************************** 18. row ***************************
Variable_name: binlog_rows_query_log_events
        Value: OFF
*************************** 19. row ***************************
Variable_name: binlog_stmt_cache_size
        Value: 32768
*************************** 20. row ***************************
Variable_name: binlog_transaction_dependency_history_size
        Value: 25000
*************************** 21. row ***************************
Variable_name: binlog_transaction_dependency_tracking
        Value: COMMIT_ORDER
*************************** 22. row ***************************
Variable_name: innodb_api_enable_binlog
        Value: OFF
*************************** 23. row ***************************
Variable_name: log_statements_unsafe_for_binlog
        Value: ON
*************************** 24. row ***************************
Variable_name: max_binlog_cache_size
        Value: 18446744073709547520
*************************** 25. row ***************************
Variable_name: max_binlog_size
        Value: 1073741824
*************************** 26. row ***************************
Variable_name: max_binlog_stmt_cache_size
        Value: 18446744073709547520
*************************** 27. row ***************************
Variable_name: sync_binlog
        Value: 1

**Comment by dyipon** [comment]
I got the same error message. Anybody found a solution?

**Comment by dyipon** [comment]
I just realized it's working in spite of error message. (ps aux | grep proxysql)
And don't forget to enable slave binary logs :)

**Comment by adepollusaikumar** [comment]
I'm getting the same error for ubuntu 18.04 . is there any workaround?

2020-06-16 19:09:23 [INFO] Reading binlogs...
Invalid Format_description event: number_of_event_types 39 > 38
Met exception in get_remote_binlog cycle. Message: Invalid Format_description event
