### ISSUE TITLE
Won't compile on Centos 7

### ISSUE THREAD

**Issue by rhunton** [sysown/proxysql_mysqlbinlog#5]
Could you please provide detailed instructions on how to build this?  Our developers have been unable to compile this successfully.  I'm surprised that a feature that provides such important functionality for Proxysql isn't more mature and fully integrated into the product ecosystem.  We haven't been able to locate any documentation for implementation either other than a couple of slide presentations.

Thank you.

The last error we encountered was:
`dev1 proxysql_mysqlbinlog-master]$ make
g++ -o proxysql_binlog_reader proxysql_binlog_reader.cpp -std=c++11 -ggdb ./libslave/libslave.a ./libev/.libs/libev.a libdaemon/libdaemon/.libs/libdaemon.a -I./libslave/ -I./libev/ -I./libdaemon/ -rdynamic -lz -ldl -lssl -lcrypto -lpthread -lboost_system -lrt -Wl,-Bstatic -lmysqlclient -Wl,-Bdynamic -ldl -lssl -lcrypto -pthread
/usr/bin/ld: cannot find -lmysqlclient
collect2: error: ld returned 1 exit status
make: *** [proxysql_binlog_reader] Error 1`

**Comment by altmannmarcelo** [comment]
Hi @rhunton 

Can you please try:

```
ln -s /usr/lib64/mysql/libmysqlclient.a /usr/lib64/libmysqlclient.a
```

**Comment by rhunton** [comment]
Thank you, that seems to have worked!
